<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-ders_programi_yonetim_sistemi-fed411c2-82ee-4d04-b7e2-30106fc91bfc</UserSecretsId>
    <RootNamespace>ders_programi_yonetim_sistemi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.25" />
  </ItemGroup>

</Project>
